!br.ufrj.cos.cli.LearningFromFilesCLI

knowledgeBaseFilePaths:
theoryFilePaths:
exampleFilePaths:
outputDirectoryPath:

knowledgeBaseCollectionClassName:   java.util.ArrayList
knowledgeBasePredicateClassName:    br.ufrj.cos.knowledge.filter.GroundedFactPredicate
knowledgeBaseAncestralClassName:    br.ufrj.cos.logic.Atom
theoryCollectionClassName:          java.util.ArrayList
theoryPredicateClassName:
theoryBaseAncestralClassName:

controlConcurrence:           false
loadedPreTrainedParameters:   false
passAllExampleAtOnce:         false
examplesBatchSize:            1

engineSystemTranslator: !br.ufrj.cos.engine.proppr.ProPprEngineSystemTranslator
   useTernayIndex:         false
   numberOfTrainingEpochs: 5
   numberOfThreads:        1
   normalizeAnswers:       true
   aprOptions: !edu.cmu.ml.proppr.util.APROptions
      epsilon:    1e-4
      alpha:      0.1
      maxDepth:   20
      traceDepth: 0
      traceRoot:  0
      stopEarly:  -1
   regularize:          !edu.cmu.ml.proppr.learn.RegularizeL2 {}
   prover:              !edu.cmu.ml.proppr.prove.DprProver {}
   squashingFunction:   !edu.cmu.ml.proppr.learn.tools.ClippedExp {}

theoryMetrics:
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.AccuracyMetric  {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.PrecisionMetric {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.RecallMetric    {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.F1ScoreMetric   {}

   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.LikelihoodMetric    {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.LogLikelihoodMetric {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.RocCurveMetric      {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.PrecisionRecallCurveMetric {}

revisionOperatorSelector:  !br.ufrj.cos.knowledge.theory.manager.revision.BestRevisionOperatorSelector {}
theoryEvaluator:           !br.ufrj.cos.knowledge.theory.evaluation.TheoryEvaluator {}
theoryRevisionManager:     !br.ufrj.cos.knowledge.theory.manager.HoeffdingBoundTheoryManager
   theoryMetric:           &metric !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.RocCurveMetric {}
   delta:                  1e-6
   trainUsingAllExamples:  true

incomingExampleManager:    !br.ufrj.cos.knowledge.manager.TreeExampleManager
   sampleSelector:   !br.ufrj.cos.knowledge.theory.manager.revision.point.IndependentSampleSelector
      relevantDepth: 0
   treeTheory:       &tree !br.ufrj.cos.knowledge.manager.TreeTheory {}

revisionManager:  !br.ufrj.cos.knowledge.theory.manager.revision.BestLeafRevisionManager
   numberOfLeavesToRevise: 1
   treeTheory:             *tree
   revisionHeuristic:      !br.ufrj.cos.knowledge.theory.manager.revision.heuristic.EntropyHeuristic {}

revisionOperatorEvaluators:
   - !br.ufrj.cos.knowledge.theory.manager.revision.RevisionOperatorEvaluator
      revisionOperator:    !br.ufrj.cos.knowledge.theory.manager.revision.operator.tree.AddNodeTreeRevisionOperator
         treeTheory:       *tree
         refine:                       false
         maximumSideWayMovements:      0
         improvementThreshold:         0.0
         generic:                      true
         theoryMetric:           *metric
         appendOperator:         !br.ufrj.cos.knowledge.theory.manager.revision.operator.RelevantLiteralAppendOperator
            theoryMetric:        *metric
            numberOfThreads:     1
            evaluationTimeout:   30
            relevantsDepth:      0
   - !br.ufrj.cos.knowledge.theory.manager.revision.RevisionOperatorEvaluator
         revisionOperator:   !br.ufrj.cos.knowledge.theory.manager.revision.operator.tree.RemoveNodeTreeRevisionOperator
            treeTheory:       *tree
