!br.ufrj.cos.cli.LearningFromFilesCLI

knowledgeBaseFiles:
theoryFiles:
exampleFiles:

knowledgeBaseCollectionClassName:   java.util.ArrayList
knowledgeBasePredicateClassName:    br.ufrj.cos.knowledge.filter.GroundedFactPredicate
knowledgeBaseAncestralClassName:    br.ufrj.cos.logic.Atom
theoryCollectionClassName:          java.util.ArrayList
theoryPredicateClassName:
theoryBaseAncestralClassName:

controlConcurrence: false

engineSystemTranslator: !br.ufrj.cos.engine.proppr.ProPprEngineSystemTranslator
   useTernayIndex:         false
   numberOfTrainingEpochs: 5
   numberOfThreads:        1
   normalizeAnswers:       true
   aprOptions: !edu.cmu.ml.proppr.util.APROptions
      epsilon:    1e-4
      alpha:      0.1
      maxDepth:   20
      traceDepth: 0
      traceRoot:  0
      stopEarly:  -1
   regularize:          !edu.cmu.ml.proppr.learn.RegularizeL2 {}
   prover:              !edu.cmu.ml.proppr.prove.DprProver {}
   squashingFunction:   !edu.cmu.ml.proppr.learn.tools.ClippedExp {}

theoryMetrics:
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.AccuracyMetric  {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.PrecisionMetric {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.RecallMetric    {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.F1ScoreMetric   {}

   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.LikelihoodMetric    {}
   - !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.LogLikelihoodMetric {}

revisionOperatorEvaluators:
   - !br.ufrj.cos.knowledge.theory.manager.revision.operator.RevisionOperatorEvaluator
      revisionOperator: !br.ufrj.cos.knowledge.theory.manager.revision.operator.generalization.BottomClauseBoundedRule
         theoryMetric:     !br.ufrj.cos.knowledge.theory.evaluation.metric.probabilistic.LogLikelihoodMetric {}
         variableGeneratorClassName:   br.ufrj.cos.util.VariableGenerator
         relevantsDepth:               0
         maximumSideWayMovements:      -1
         improvementThreshold:         0.0
         generic:                      true
         evaluationTimeout:            300
         numberOfThreads:              1
         internalMetric:   !br.ufrj.cos.knowledge.theory.evaluation.metric.logic.F1ScoreMetric {}

revisionOperatorSelector: !br.ufrj.cos.knowledge.theory.manager.revision.operator.SelectFirstRevisionOperator {}
revisionManager: !br.ufrj.cos.knowledge.theory.manager.revision.RevisionManager {}
incomingExampleManager: !br.ufrj.cos.knowledge.manager.ReviseAllIncomingExample {}
theoryEvaluator: !br.ufrj.cos.knowledge.theory.evaluation.TheoryEvaluator {}
theoryRevisionManager: !br.ufrj.cos.knowledge.theory.manager.TheoryRevisionManager {}
